### ISSUE TITLE
Expression "add advancement" adds many advancements instead of just one

### ISSUE THREAD

**Issue by takatalvi** [hotpocket184/skript-advancements#14]
Hi, I think the "add advancement" functionality is not working as intended. While I expected it to be similar to the vanilla command `/advancement grant player only ...`, it somehow adds many more advancements at once. In one instance, it granted me all the pre-requisite advancements, along with the ones I already had. In another instance, it gave another player **all** the vanilla advancements, except for "nether/return_to_sender", which seems kinda random. I wasn't able to identify a definite pattern but it seems to grant already achieved advancements, most often those which are related to the one requested.

My script is as follows:
```
on right click:
    if clicked block is dragon_egg:
        if the player's advancements contain advancement "minecraft:end/kill_dragon":
            if the player's advancements don't contain advancement "minecraft:end/dragon_egg":
                add advancement "minecraft:end/dragon_egg" to the player's advancements
        cancel event
```

The conditions work as expected and they don't seem to be the issue. I debugged with some broadcasts and conditions were recognized correctly. I also tried a simplified version without advancement conditions:
```
on right click:
    if clicked block is stone:
        add advancement "minecraft:end/dragon_egg" to the player's advancements
```
 The result is always the same - the player gets a lot more advancements than specified. In my opinion, the "add advancement" expression could mirror the vanilla command. That grants only the specified advancement regardless of pre-requisites or dependencies. Also, if the player already has the specified advancement, it's not granted a second time.

Thank you!

**Comment by hotpocket184** [comment]
This has been fixed, thank you!

**Comment by takatalvi** [comment]
Hi, thanks for looking into this! I've tried to test it but somehow I can't get it to work now. The script that worked previously (although it granted several advancements at once) gives me an error on reload now:

![image](https://user-images.githubusercontent.com/35687568/209124708-268e7ced-06a1-4183-b56d-07e10344f8e9.png)

This is the script, I've followed the info on the Wiki section, tried many different formulations but it always boils down to the error above.
```
on right click:
    if clicked block is dragon_egg:
        if the player's advancements contain advancement "minecraft:end/kill_dragon":
            if the player's advancements don't contain advancement "minecraft:end/dragon_egg":
                add advancement "minecraft:end/dragon_egg" to the player's advancements
        cancel event
```

Thanks!

**Comment by hotpocket184** [comment]
It seems to work for me using the exact script. Try it on 1.4.2 to see if it works then since that is what I am using.

**Comment by takatalvi** [comment]
Hi, I made sure to update Paper, Skript and Skript-Advancements, which is now on 1.4.2, as you mentioned. Unfortunately, reloading my script behaves exactly the same as before, it says "... is not a location" :/

What's new, however, is that on server startup, I'm now getting some exceptions when plugins are being loaded. First it's this:

```
...
[12:34:50 INFO]: [Skript] Loading Skript v2.6.4
[12:34:50 INFO]: [WorldEditSUI] Loading WorldEditSUI v1.7.2
[12:34:50 INFO]: [EssentialsDiscord] Loading EssentialsDiscord v2.20.0-dev+20-582a357
[12:34:50 INFO]: [Skript-Advancements] Loading Skript-Advancements v1.4.2
[12:34:50 INFO]: [UltimateAdvancementAPI] Can't find Wrapper Class! (com.fren_gor.ultimateAdvancementAPI.nms.v1_19_R2.MinecraftKeyWrapper_v1_19_R2)
[12:34:50 ERROR]: [org.bukkit.craftbukkit.v1_19_R2.CraftServer] null initializing Skript-Advancements v1.4.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
at com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.<clinit>(AdvancementUtils.java:46) ~[skriptadvancements-1.4.2.jar:?]
at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.load(AdvancementMain.java:93) ~[skriptadvancements-1.4.2.jar:?]
at me.hotpocket.skriptadvancements.SkriptAdvancements.onLoad(SkriptAdvancements.java:32) ~[skriptadvancements-1.4.2.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:442) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-350]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructor(java.lang.Class[])" because "clazz" is null
at com.fren_gor.ultimateAdvancementAPI.nms.wrappers.MinecraftKeyWrapper.<clinit>(MinecraftKeyWrapper.java:19) ~[skriptadvancements-1.4.2.jar:?]
... 8 more
[12:34:50 INFO]: [SkQuery] Loading SkQuery v4.1.8
...
```

And then when initializing, I'm getting this:
```
...
[12:35:07 INFO]: [Skript-Advancements] Enabling Skript-Advancements v1.4.2
[12:35:07 ERROR]: Error occurred while enabling Skript-Advancements v1.4.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.commonEnablePreDatabase(AdvancementMain.java:183) ~[skriptadvancements-1.4.2.jar:?]
at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.enableSQLite(AdvancementMain.java:120) ~[skriptadvancements-1.4.2.jar:?]
at me.hotpocket.skriptadvancements.SkriptAdvancements.onEnable(SkriptAdvancements.java:39) ~[skriptadvancements-1.4.2.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-350]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-350]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:35:07 INFO]: [Skript-Advancements] Disabling Skript-Advancements v1.4.2
[12:35:07 ERROR]: Error occurred while disabling Skript-Advancements v1.4.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.disable(AdvancementMain.java:236) ~[skriptadvancements-1.4.2.jar:?]
at me.hotpocket.skriptadvancements.SkriptAdvancements.onDisable(SkriptAdvancements.java:60) ~[skriptadvancements-1.4.2.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:400) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:581) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:375) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-350]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-350]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-350]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:35:07 INFO]: [SkQuery] Enabling SkQuery v4.1.8
...
```

It looks like a pre-requisite is missing, but I guess it's something that is bundled with the plugin. I only have the main Skript plugin (2.6.4), SkQuery (4.1.8) and Skript-Advancements (1.4.2).

Thank you for looking into this!

**Comment by hotpocket184** [comment]
I'll check it out. Make sure you are not on 1.19.3 since it does not work on that version.

**Comment by takatalvi** [comment]
Oh, that's most likely the issue, I'm running Paper 1.19.3. I guess I'll have to wait until it's supported to test it. Thank you for your work!

**Comment by hotpocket184** [comment]
See if this works: [https://github.com/hotpocket184/skript-advancements/releases/tag/1.5.0](https://github.com/hotpocket184/skript-advancements/releases/tag/1.5.0)

**Comment by takatalvi** [comment]
Wow, I didn't expect a new version so fast! I can happily confirm that it's working as expected on 1.19.3. The syntax I used only grants the advancement it's supposed to grant.

Thank you so much!
