### ISSUE TITLE
1.19.3 incompatible

### ISSUE THREAD

**Issue by AuthenTiiq** [hotpocket184/skript-advancements#19]
Hello,

The plugin is not working since 1.19.3, is there an update coming soon to support it?

I have 2 errors in my console
```log
[UltimateAdvancementAPI] Can't find Wrapper Class! (com.fren_gor.ultimateAdvancementAPI.nms.v1_19_R2.MinecraftKeyWrapper_v1_19_R2)
[20:34:23] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_19_R2.CraftServer] null initializing Skript-Advancements v1.4.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.<clinit>(AdvancementUtils.java:46) ~[skriptadvancements-1.4.0.jar:?]
	at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.load(AdvancementMain.java:93) ~[skriptadvancements-1.4.0.jar:?]
	at me.hotpocket.skriptadvancements.SkriptAdvancements.onLoad(SkriptAdvancements.java:32) ~[skriptadvancements-1.4.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:307) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructor(java.lang.Class[])" because "clazz" is null
	at com.fren_gor.ultimateAdvancementAPI.nms.wrappers.MinecraftKeyWrapper.<clinit>(MinecraftKeyWrapper.java:19) ~[skriptadvancements-1.4.0.jar:?]
	... 8 more
```

```log

[Server thread/ERROR]: Error occurred while enabling Skript-Advancements v1.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
	at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.commonEnablePreDatabase(AdvancementMain.java:183) ~[skriptadvancements-1.4.0.jar:?]
	at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.enableSQLite(AdvancementMain.java:120) ~[skriptadvancements-1.4.0.jar:?]
	at me.hotpocket.skriptadvancements.SkriptAdvancements.onEnable(SkriptAdvancements.java:39) ~[skriptadvancements-1.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:336) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:34:41] [Server thread/INFO]: [Skript-Advancements] Disabling Skript-Advancements v1.4.0
[20:34:41] [Server thread/ERROR]: Error occurred while disabling Skript-Advancements v1.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
	at com.fren_gor.ultimateAdvancementAPI.AdvancementMain.disable(AdvancementMain.java:236) ~[skriptadvancements-1.4.0.jar:?]
	at me.hotpocket.skriptadvancements.SkriptAdvancements.onDisable(SkriptAdvancements.java:60) ~[skriptadvancements-1.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:587) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:336) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1860]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

thank

**Comment by hotpocket184** [comment]
I'll check it out. I have an idea as to what it could be.

**Comment by hotpocket184** [comment]
The API used does not yet support 1.19.3.

**Comment by AuthenTiiq** [comment]
Is it planned to be supported in the future?

**Comment by hotpocket184** [comment]
I believe so.

**Comment by rudde0** [comment]
> The API used does not yet support 1.19.3.

Could you try with this one? https://jenkins.frengor.com/job/UltimateAdvancementAPI/job/dev/88/

**Comment by hotpocket184** [comment]
Yes I can try.

**Comment by frengor** [comment]
We (@EscanorTargaryen and I) have updated UltimateAdvancementAPI, now it supports 1.19.3.

@hotpocket184 We also noted you're using our API, great job! If you have any question or want to have updates on WIP features (we're planning a breaking change which will however enable support for stuff like hex colors) feel free to join our discord.

**Comment by hotpocket184** [comment]
Thank you very much! I feel honored that you have found this if that makes any sense. I will for sure join the discord.
