### ISSUE TITLE
Errors in 1.20.4

### ISSUE THREAD

**Issue by JakeGBLP** [hotpocket184/skript-advancements#40]
```
[17:02:30 INFO]: Paper: Using Java cipher from Velocity.
[17:02:30 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins\skript-citizens-1.0.0.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Citizens]. Please download and install these plugins to run 'skript-citizens'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:02:31 INFO]: [Skript] Loading server plugin Skript v2.8.0
[17:02:31 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[17:02:34 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.117
[17:02:40 INFO]: [VoidGen] Loading server plugin VoidGen v2.2.1
[17:02:40 INFO]: [Skript-Advancements] Loading server plugin Skript-Advancements v1.5.7
[17:02:40 INFO]: [UltimateAdvancementAPI] Can't find Wrapper Class! (me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.nms.v1_20_R3.MinecraftKeyWrapper_v1_20_R3)
[17:02:40 ERROR]: [Skript-Advancements] Error initializing plugin 'skriptadvancements-1.5.7.jar' in folder 'plugins' (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.<clinit>(AdvancementUtils.java:46) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.load(AdvancementMain.java:93) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onLoad(SkriptAdvancements.java:41) ~[skriptadvancements-1.5.7.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructor(java.lang.Class[])" because "clazz" is null
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.nms.wrappers.MinecraftKeyWrapper.<clinit>(MinecraftKeyWrapper.java:19) ~[skriptadvancements-1.5.7.jar:?]
        ... 12 more
        

------------------------------
(happens a bit after)

        
        
[17:03:24 ERROR]: Error occurred while enabling Skript-Advancements v1.5.7 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.commonEnablePreDatabase(AdvancementMain.java:183) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.enableSQLite(AdvancementMain.java:120) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onEnable(SkriptAdvancements.java:48) ~[skriptadvancements-1.5.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:03:24 INFO]: [Skript-Advancements] Disabling Skript-Advancements v1.5.7
[17:03:24 ERROR]: Error occurred while disabling Skript-Advancements v1.5.7
java.lang.NoClassDefFoundError: Could not initialize class me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.disable(AdvancementMain.java:236) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onDisable(SkriptAdvancements.java:76) ~[skriptadvancements-1.5.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by hotpocket184** [comment]
I didn't even know 1.20.4 was a version. It might be updated eventually.

**Comment by erenkarakal** [comment]
A new update was released.
