### ISSUE TITLE
Error in console when a player completes an advancement

### ISSUE THREAD

**Issue by zombieman2020** [hotpocket184/skript-advancements#8]
So when a player completes an advancement the error below always shows in the console. I believe I'm currently on the latest version of the Skript plugin and Skript-Advancements since I downloaded them recently, but I could be wrong. I also will include the .sk file in this issue so that you can see what code I have that the error is originating from. The script code is not included in the error in the console btw.

```
on advancement complete:
    replace all "%the player%" with "<yellow>%the player%<gray>" in the advancement message


- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! [Skript] Severe Error:
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Something went horribly wrong with Skript.
- [Mon 17:41:54 ERROR Minecraft] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
- [Mon 17:41:54 ERROR Minecraft] #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
- [Mon 17:41:54 ERROR Minecraft] #!#! Here is full list of them:
- [Mon 17:41:54 ERROR Minecraft] #!#! Graves v4.9 Skript-Advancements v1.3.4 SkBee v2.3.0 (https://github.com/ShaneBeee/SkBee) DiscordSRV v1.25.1 (https://github.com/DiscordSRV/DiscordSRV) 
- [Mon 17:41:54 ERROR Minecraft] #!#! We could not identify which of those are specially related, so this might also be Skript issue.
 
- [Mon 17:41:54 ERROR Minecraft] #!#! You should try disabling those plugins one by one, trying to find which one causes it.
- [Mon 17:41:54 ERROR Minecraft] #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
- [Mon 17:41:54 ERROR Minecraft] #!#! In that case, you will be given instruction on how should you report it.
- [Mon 17:41:54 ERROR Minecraft] #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
- [Mon 17:41:54 ERROR Minecraft] #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Stack trace:
- [Mon 17:41:54 ERROR Minecraft] #!#! java.lang.NullPointerException: input
- [Mon 17:41:54 ERROR Minecraft] #!#!     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:79)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at skriptadvancements-1.3.4.jar//me.hotpocket.skriptadvancements.elements.expressions.ExprAdvancementMessage.get(ExprAdvancementMessage.java:57)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at skriptadvancements-1.3.4.jar//me.hotpocket.skriptadvancements.elements.expressions.ExprAdvancementMessage.get(ExprAdvancementMessage.java:18)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:73)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.effects.EffReplace.execute(EffReplace.java:92)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.AdvancementDataPlayer.a(AdvancementDataPlayer.java:294)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.advancements.CriterionTrigger$a.a(CriterionTrigger.java:35)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.advancements.critereon.CriterionTriggerAbstract.a(CriterionTriggerAbstract.java:73)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.advancements.critereon.CriterionTriggerInventoryChanged.a(CriterionTriggerInventoryChanged.java:57)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.advancements.critereon.CriterionTriggerInventoryChanged.a(CriterionTriggerInventoryChanged.java:53)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.level.EntityPlayer$2.a(EntityPlayer.java:316)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.world.inventory.Container.a(Container.java:304)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.world.inventory.Container.d(Container.java:241)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.commands.CommandGive.a(CommandGive.java:69)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.commands.CommandGive.lambda$register$1(CommandGive.java:33)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2293)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2247)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1361)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1338)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1331)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1309)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1197)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
- [Mon 17:41:54 ERROR Minecraft] #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Version Information:
- [Mon 17:41:54 ERROR Minecraft] #!#!   Skript: 2.6.3 (latest)
- [Mon 17:41:54 ERROR Minecraft] #!#!     Flavor: skriptlang-github
- [Mon 17:41:54 ERROR Minecraft] #!#!     Date: 00:55:22.847925631
- [Mon 17:41:54 ERROR Minecraft] #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
- [Mon 17:41:54 ERROR Minecraft] #!#!   Minecraft: 1.19.2
- [Mon 17:41:54 ERROR Minecraft] #!#!   Java: 17 (OpenJDK 64-Bit Server VM 17+20-202105042342)
- [Mon 17:41:54 ERROR Minecraft] #!#!   OS: Linux amd64 4.18.0-348.2.1.el8_5.x86_64
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Server platform: Paper
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Current node: null
- [Mon 17:41:54 ERROR Minecraft] #!#! Current item: replace "%the player%" in the advancement message with "%the player%"(case sensitive: false)
- [Mon 17:41:54 ERROR Minecraft] #!#! Current trigger: advancement complete (simple event) (advancements.sk, line 1)
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Thread: Server thread
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! Language: english
- [Mon 17:41:54 ERROR Minecraft] #!#! Link parse mode: DISABLED
- [Mon 17:41:54 ERROR Minecraft] #!#! 
- [Mon 17:41:54 ERROR Minecraft] #!#! End of Error.
- [Mon 17:41:54 ERROR Minecraft] #!#!

**Comment by hotpocket184** [comment]
Thanks for making an issue. It looks like I only made the advancement message expression allow setting, not replacing. I'll be sure to add that in the next update.

This should help:
```
set {_message} to advancement message
replace all "%player%" with "<yellow>%player%<reset>" in {_message}
set advancement message to {_message}
```
