### ISSUE TITLE
Error in console when a player completes an advancement... x2

### ISSUE THREAD

**Issue by NerfOscar** [hotpocket184/skript-advancements#9]
So, when a player completes an advancement this error always shows in the console... And no, it is not the same one that  @/zombieman2020 reported, but its kind of similar.

At the start, I got the same error than zombieman2022 while using this code:
`on advancement:`
`    set {_message} to advancement message`
`    replace "%player%" with "&3&o&kplayer00000000&r" in advancement message`
 
 Then, I saw a reply suggesting this as a temporal fix:
`on advancement:`
`    set {_message} to advancement message`
`    replace all "%player%" with "&3&o&kplayer00000000" in advancement message`
`    set advancement message to {_message}`
 
And that caused this new error:
```[22:00:48 ERROR]: #!#! [Skript] Severe Error:
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Something went horribly wrong with Skript.
[22:00:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:00:48 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:00:48 ERROR]: #!#! Here is full list of them:
[22:00:48 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) Skript-Advancements v1.3.4 DiSky v4.4.0 SkBee v1.16.3 (https://github.com/ShaneBeee/SkBee) Skore v2.0.5 
[22:00:48 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:00:48 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:00:48 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:00:48 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:00:48 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:00:48 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Stack trace:
[22:00:48 ERROR]: #!#! java.lang.NullPointerException: input
[22:00:48 ERROR]: #!#!     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[22:00:48 ERROR]: #!#!     at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:79)
[22:00:48 ERROR]: #!#!     at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75)
[22:00:48 ERROR]: #!#!     at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306)
[22:00:48 ERROR]: #!#!     at skriptadvancements-1.3.4.jar//me.hotpocket.skriptadvancements.elements.expressions.ExprAdvancementMessage.get(ExprAdvancementMessage.java:57)
[22:00:48 ERROR]: #!#!     at skriptadvancements-1.3.4.jar//me.hotpocket.skriptadvancements.elements.expressions.ExprAdvancementMessage.get(ExprAdvancementMessage.java:18)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[22:00:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[22:00:48 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[22:00:48 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:00:48 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.AdvancementDataPlayer.a(AdvancementDataPlayer.java:298)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.commands.CommandAdvancement$Action$1.a(CommandAdvancement.java:158)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.commands.CommandAdvancement$Action.a(CommandAdvancement.java:201)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.commands.CommandAdvancement.a(CommandAdvancement.java:64)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.commands.CommandAdvancement.g(CommandAdvancement.java:41)
[22:00:48 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[22:00:48 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178)
[22:00:48 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:299)
[22:00:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[22:00:48 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[22:00:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2390)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2182)
[22:00:48 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[22:00:48 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[22:00:48 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:00:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:00:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1427)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[22:00:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1404)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1397)
[22:00:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1375)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1257)
[22:00:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[22:00:48 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Version Information:
[22:00:48 ERROR]: #!#!   Skript: 2.6.3 (latest)
[22:00:48 ERROR]: #!#!     Flavor: skriptlang-github
[22:00:48 ERROR]: #!#!     Date: 00:55:22.847925631
[22:00:48 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[22:00:48 ERROR]: #!#!   Minecraft: 1.18.2
[22:00:48 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[22:00:48 ERROR]: #!#!   OS: Linux amd64 5.4.0-126-generic
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Server platform: Paper
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Current node: null
[22:00:48 ERROR]: #!#! Current item: set {_message} (as java.lang.Object) to the advancement message
[22:00:48 ERROR]: #!#! Current trigger: advancement (simple event) (uhc-chat.sk, line 28)
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Thread: Server thread
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! Language: english
[22:00:48 ERROR]: #!#! Link parse mode: DISABLED
[22:00:48 ERROR]: #!#! 
[22:00:48 ERROR]: #!#! End of Error.
[22:00:48 ERROR]: #!#! ```

**Comment by NerfOscar** [comment]
Just figured out that the addon got updated at the same time that I reported this bug... Well, it got fixed.
